name: Build release

on:
  push:
    tags: [ v* ]

permissions:
  contents: write

jobs:
  release:
    name: Build release
    runs-on: ubuntu-22.04
    env:
      GO_VERSION: 1.19.4
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: goreleaser/goreleaser-action@v4
        with:
          version: v1.14.1
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
