name: Build release image

on:
  release:
    types: [ published ]

jobs:
  build:
    name: Build release image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: arisudesu
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}

      - run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - uses: docker/build-push-action@v2
        with:
          context: .
          tags: ghcr.io/arisudesu/socks-proxy:${{ env.VERSION }}
          push: true
